### ISSUE TITLE
http://adplug.github.io/libbinio/ does not point to 1.5 documentation

### ISSUE THREAD

**Issue by coldtobi** [adplug/libbinio#10]
The latest link is for the 1.4 docu…

**Comment by Malvineous** [comment]
Could you submit a PR with the fixes?

**Comment by coldtobi** [comment]
I have no idea how the project creates the website.

**Comment by coldtobi** [comment]
Edit: Corrected title, had the wrong URL (meant http://adplug.github.io/libbinio/)

**Comment by Malvineous** [comment]
Unfortunately I don't know either, it's in the gh-pages branch (https://github.com/adplug/libbinio/tree/gh-pages) but I'm not sure whether it was automatically generated or done manually.  Let me know if you work out how it was done.

**Comment by Malvineous** [comment]
Seems to have updated now
