### ISSUE TITLE
Please upload the real releases to GitHub

### ISSUE THREAD

**Issue by jlindgren90** [adplug/libbinio#3]
The tarballs on GitHub are just Git snapshots and are missing (for example) the ./configure script.

The real release tarballs are still available on SourceForge for now, but it would be nice to have everything in one place.

**Comment by mywave82** [comment]
debian/ubuntu have cherry-picked some patches over the years due to lack of release

**Comment by Malvineous** [comment]
I've uploaded the latest one, hopefully that will be enough.  If the off-by-one fix can be confirmed then I'll release the latest git as 1.5
