### ISSUE TITLE
Undocumented Build Dependency

### ISSUE THREAD

**Issue by cdr255** [adplug/libbinio#5]
## INSTALL does not mention texinfo

**Proposed Solution:** Add mention of texinfo as a dependency to section of INSTALL that suggests `autoreconf --install`.

### Details

Since You need to have GNU texinfo installed in order to build this project, it should be listed as a dependency somewhere in the README or INSTALL. Not all distributions come with texinfo installed; OpenSUSE does not, nor does it include it in any kind of "build-essential"-esque pattern I'm aware of. It's entirely possible to have autotools installed without having texinfo installed.

Since You are already assuming potential users don't know to run `autoreconf --install` on a cloned project, expecting them to know about texinfo (which may or may not be installed, especially since manpages are still more common) is dubious.

**Comment by Malvineous** [comment]
Can you submit a PR for these changes so we can be sure it's explained correctly?

**Comment by Malvineous** [comment]
Many thanks!
